### ISSUE TITLE
Move jsDelivr back to `geolocation-cn`

### ISSUE THREAD

**Issue by kidonng** [v2ray/domain-list-community#147]
https://github.com/v2ray/domain-list-community/commit/c7c30b4108de30e2e2255e1fec6b19e0e7ba527f (and following #128) seem like false positives. There's no sign jsDelivr has stopped partnering with QUANTIL (and therefore lost access points in China). [A simple test](http://tool.chinaz.com/speedtest.aspx?host=https://cdn.jsdelivr.net/npm/jquery@3.2.1/dist/jquery.min.js) should be enough evidence.
Since there may be others in know, I choose to submit an issue here before a PR to move.

**Comment by kslr** [comment]
see https://github.com/jsdelivr/jsdelivr#china
cc @akiirui do you need further clarification?

**Comment by akiirui** [comment]
> see https://github.com/jsdelivr/jsdelivr#china
> cc @akiirui do you need further clarification?

I just clean duplication rules, and I didn't check the location. Sorry for this.

Because c7c30b4108de30e2e2255e1fec6b19e0e7ba527f, let me think jsDelivr are not in `geolocation-cn`.
So, I deleted these.

If *jsDelivr works perfectly inside China!*, We need delete `include:jsdelivr` in `geolocation-!cn`, and add back to `geolocation-cn`.

**Comment by akiirui** [comment]
Sorry for my carelessness.

I commit a patch, add jsdelivr back to `geolocation-cn` and delete from `geolocation-!cn`

**Comment by kidonng** [comment]
@akiirui don't blame yourself, I just happened to discover this mistake. Since the rules have been updated, we can close this now.
